% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.11 (R2021b) and Automated Driving Toolbox 3.4 (R2021b).
% Generated on: 27-Jul-2022 15:59:12

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0 0 0;
    100 0 0];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Length', 5, ...
    'Position', [2.2 -1.9 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [2.2 -1.9 0;
    5 -1.9 0;
    15 -1.9 0;
    18 1.9 0;
    21 1.9 0;
    24 1.9 0;
    30 1.9 0;
    100 1.9 0];
speed = [20;20;20;20;20;20;20;20];
waittime = [0;0;0;0;0;0;0;0];
trajectory(egoVehicle, waypoints, speed, waittime);
%record the scenario
rec=record(scenario);
yaw=[];
y=[];%lateral position
x=[];%longitudnal position
t=[];
for i = 1: length(rec)
    yaw(i)=deg2rad(rec(i).ActorPoses(1).Yaw);
    x(i)=rec(i).ActorPoses(1).Position(1);
    y(i)=rec(i).ActorPoses(1).Position(2);
    v(i)=norm(rec(i).ActorPoses(1).Velocity);
    t(i)=rec(i).SimulationTime;
end
yaw_angle=[t' yaw'];
lateral_position=[t' y'];
velocity=[t' v'];
longitudnal_position=[t' x'];
initial_state=[rec(1).ActorPoses(1).Position(1);rec(1).ActorPoses(1).Position(2);deg2rad(rec(1).ActorPoses(1).Yaw);speed(1)];